name: 'Install dependencies'
description: 'Installs dependencies'
runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash
    - run: nom i @rollup/rollup-linux-x64-gnu
      shell: bash
