name: Release Train

on:
    push:
        branches: ["main"]

permissions:
    contents: write
    pull-requests: write

env:
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
    release-train:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version-file: .nvmrc
                cache: "npm"
            - uses: ./.github/actions/install
            - uses: ./.github/actions/lint
            - uses: ./.github/actions/build
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                release-type: node
            - uses: ./.github/actions/publish
              if: ${{ steps.release.outputs.release_created }}
